services:
  web1:
    build: ./web1
    container_name: web1

  web2:
    build: ./web2
    container_name: web2

  web3:
    build: ./web3
    container_name: web3

  proxy:
    image: nginx:1.25-alpine
    container_name: proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
      - web2
      - web3
